baseURL = 'https://ijimiji.github.io/'
languageCode = 'en-us'
title = "@ijimiji's blog"
theme = 'hugo-PaperMod'

[[menu.main]]
name = "Home"
url = "/"
weight = 1

[[menu.main]]
name = "CV"
url = "/cv/index.html"
weight = 2